apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
  annotations:
    build-date: "2026-05-23"
    build-version: "1.0.0"
    build-user: "jordanhuaman"
    build-email: "jordanhuaman@gmail.com"
    build-url: "https://github.com/jordanhuaman/kubia"
    build-tag: "latest"
    build-branch: "main"
    build-commit: "1234567890"
spec:
  containers:
  - image: jordanhuaman/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP